name: Android Build

on:
  pull_request:
    branches: ["main"]
    paths:
      - "app/**"
  push:
    branches: ["main"]
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: List files in working directory
        run: ls -la

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build app with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v
        with:
          name: DSLearn-release.apk
          path: app/build/outputs/apk/release/app-release.apk
