name: Build Android and Backend

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]

jobs:
  android:
    uses: ./.github/workflows/android_build.yml

  backend:
    uses: ./.github/workflows/backend_build.yml